version: '3.8'

services:
  techdome-backend:
    build:
      context: ./Techdome-backend
    image: techdome-backend-img
    environment:
      - DB=mongodb://54.159.149.90/
      - PORT=5000
    ports:
      - "5000:5000"
    container_name: techdome-backend

  techdome-frontend:
    build:
      context: ./Techdome-frontend
    image: techdome-frontend-img
    environment:
      - REACT_APP_BASE_URL=http://54.159.149.90/api
    ports:
      - "80:80"
    container_name: techdome-frontend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - techdome-network
    container_name: techdome-frontend

volumes:
  mongo-data:

networks:
  techdome-network:
    driver: bridge

