version: '3.8'

services:
  techdome-backend:
    build:
      context: ./Techdome-backend
    image: techdome-backend-img  # Specify the image name
    environment:
      - DB=mongodb://44.211.224.244/
      - PORT=5000
    ports:
      - "5000:5000"
    container_name: techdome-backend  # Set a custom container name

  techdome-frontend:
    build:
      context: ./Techdome-frontend
    image: techdome-frontend-img  # Specify the image name
    environment:
      - REACT_APP_BASE_URL=http://44.211.224.244/api
    ports:
      - "80:80"
    container_name: techdome-frontend  # Set a custom container name

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - techdome-network
    container_name: techdome-mongo-db  # Set a custom container name

volumes:
  mongo-data:

networks:
  techdome-network:
    driver: bridge

